(push '(menu-bar-lines . nil) default-frame-alist)
(push '(tool-bar-lines . nil) default-frame-alist)
(push '(vertical-scroll-bars . nil) default-frame-alist)
;; (push '(font . "HackGen-11") default-frame-alist)
(push '(font . "Migu 1M-11") default-frame-alist)
